Stops gateway vpn client when don't have access to middle-server

diff --git a/dist/packages/triumvirate-ssvpn/upload/gateway/vpn-router-iptable-rules/vpn-router-iptable-rules b/dist/packages/triumvirate-ssvpn/upload/gateway/vpn-router-iptable-rules/vpn-router-iptable-rules
--- a/dist/packages/triumvirate-ssvpn/upload/gateway/vpn-router-iptable-rules/vpn-router-iptable-rules
+++ b/dist/packages/triumvirate-ssvpn/upload/gateway/vpn-router-iptable-rules/vpn-router-iptable-rules
@@ -48,6 +48,6 @@ if [ "$1" = start ]; then
 elif [ "$1" = stop ]; then
   del_all_rules
 else
-  echo "ERR: invalid command: ${0}" >&2
+  echo "ERR: invalid command: ${1}" >&2
   exit 1
 fi
